### ISSUE TITLE
Default installation does not work due to ng-inline-svg version

### ISSUE THREAD

**Issue by damo1884** [bitrise-io/addons-test-frontend#88]
Must run 

```
npm install ng-inline-svg@8.6.0 --save-exact
```

to fix this error with ng-inline-svg

https://github.com/arkon/ng-inline-svg/issues/125

**Comment by tadam313** [comment]
Thanks for reporting @damo1884! I'll close this issue as it was fixed in https://github.com/bitrise-io/addons-test-frontend/commit/5fda2438047559fa9ce30bc0cc51698fe04a8f49
